import { describe, expect, it } from "vitest";

import { normalizeCreateTicketInput, validateIdempotencyKey } from "../../src/ticket-validation.js";

const validBody = {
  requesterId: 1,
  categoryId: 2,
  relatedSystemId: 7,
  summary: "  Laptop battery drains quickly  ",
  description: "  The laptop battery drops below 20 percent after a short meeting.  ",
};

describe("Issue 4 create Ticket validation (UNIT-02)", () => {
  it("trims text and applies the MEDIUM priority default", () => {
    const result = normalizeCreateTicketInput(validBody);

    expect(result).toEqual({
      ok: true,
      value: {
        requesterId: 1,
        categoryId: 2,
        relatedSystemId: 7,
        summary: "Laptop battery drains quickly",
        requestedPriority: "MEDIUM",
        description: "The laptop battery drops below 20 percent after a short meeting.",
      },
    });
  });

  it("accepts the inclusive length boundaries and rejects invalid values", () => {
    const minimum = normalizeCreateTicketInput({
      ...validBody,
      summary: "12345",
      description: "12345678901234567890",
    });
    const maximum = normalizeCreateTicketInput({
      ...validBody,
      summary: "x".repeat(120),
      description: "x".repeat(2000),
    });
    const invalid = normalizeCreateTicketInput({
      ...validBody,
      summary: "  ",
      description: "too short",
      requestedPriority: "INVALID",
    });

    expect(minimum.ok).toBe(true);
    expect(maximum.ok).toBe(true);
    expect(invalid).toMatchObject({
      ok: false,
      error: {
        code: "VALIDATION_ERROR",
        fields: {
          summary: expect.any(String),
          description: expect.any(String),
          requestedPriority: expect.any(String),
        },
      },
    });
  });

  it("requires positive numeric IDs and does not accept server-generated fields", () => {
    const result = normalizeCreateTicketInput({
      ...validBody,
      requesterId: "1",
      ticketNumber: "TT-2026-000001",
    });

    expect(result).toMatchObject({
      ok: false,
      error: {
        fields: {
          requesterId: expect.any(String),
          ticketNumber: "This field is generated by the server.",
        },
      },
    });
  });

  it("accepts stable printable UUID-like idempotency keys only", () => {
    expect(validateIdempotencyKey("4f8c2a11-2f37-4fe0-a5a0")).toBe(
      "4f8c2a11-2f37-4fe0-a5a0",
    );
    expect(validateIdempotencyKey("too-short")).toBeNull();
    expect(validateIdempotencyKey("contains whitespace key")).toBeNull();
  });
});
