import { validationError } from "./errors.js";

export const REQUESTED_PRIORITIES = [
  "LOW",
  "MEDIUM",
  "HIGH",
  "URGENT",
] as const;

export type RequestedPriorityValue = (typeof REQUESTED_PRIORITIES)[number];

export interface NormalizedCreateTicketInput {
  requesterId: number;
  categoryId: number;
  relatedSystemId: number;
  summary: string;
  requestedPriority: RequestedPriorityValue;
  description: string;
}

export type CreateTicketValidationResult =
  | { ok: true; value: NormalizedCreateTicketInput }
  | { ok: false; error: ReturnType<typeof validationError> };

const SERVER_GENERATED_FIELDS = [
  "id",
  "ticketNumber",
  "ticketDate",
  "currentStatus",
  "itPriority",
  "createdAt",
  "updatedAt",
  "storageKey",
  "idempotencyKey",
  "attachments",
  "uploadedAt",
  "availabilityState",
  "removedAt",
  "removalReason",
] as const;

const CLIENT_CREATE_FIELDS = new Set([
  "requesterId",
  "categoryId",
  "relatedSystemId",
  "summary",
  "requestedPriority",
  "description",
]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isPositiveInteger(value: unknown): value is number {
  return (
    typeof value === "number" &&
    Number.isInteger(value) &&
    Number.isSafeInteger(value) &&
    value > 0
  );
}

export function normalizeCreateTicketInput(
  body: unknown,
): CreateTicketValidationResult {
  if (!isRecord(body)) {
    return {
      ok: false,
      error: validationError({ body: "A JSON object is required." }),
    };
  }

  const fields: Record<string, string> = {};

  for (const field of Object.keys(body)) {
    if (!CLIENT_CREATE_FIELDS.has(field)) {
      fields[field] = "This field is not accepted when creating a Ticket.";
    }
  }

  for (const field of SERVER_GENERATED_FIELDS) {
    if (Object.prototype.hasOwnProperty.call(body, field)) {
      fields[field] = "This field is generated by the server.";
    }
  }

  if (!isPositiveInteger(body.requesterId)) {
    fields.requesterId = "Requester ID must be a positive integer.";
  }

  if (!isPositiveInteger(body.categoryId)) {
    fields.categoryId = "Category ID must be a positive integer.";
  }

  if (!isPositiveInteger(body.relatedSystemId)) {
    fields.relatedSystemId =
      "Related System ID must be a positive integer.";
  }

  const summary = typeof body.summary === "string" ? body.summary.trim() : "";
  if (summary.length < 5 || summary.length > 120) {
    fields.summary = "Summary must be 5 to 120 characters after trimming.";
  }

  const description =
    typeof body.description === "string" ? body.description.trim() : "";
  if (description.length < 20 || description.length > 2000) {
    fields.description =
      "Description must be 20 to 2,000 characters after trimming.";
  }

  const requestedPriority =
    body.requestedPriority === undefined ? "MEDIUM" : body.requestedPriority;
  if (
    typeof requestedPriority !== "string" ||
    !REQUESTED_PRIORITIES.includes(
      requestedPriority as RequestedPriorityValue,
    )
  ) {
    fields.requestedPriority =
      "Requested priority must be LOW, MEDIUM, HIGH, or URGENT.";
  }

  if (Object.keys(fields).length > 0) {
    return { ok: false, error: validationError(fields) };
  }

  return {
    ok: true,
    value: {
      requesterId: body.requesterId as number,
      categoryId: body.categoryId as number,
      relatedSystemId: body.relatedSystemId as number,
      summary,
      requestedPriority: requestedPriority as RequestedPriorityValue,
      description,
    },
  };
}

export function validateIdempotencyKey(value: unknown): string | null {
  if (typeof value !== "string") return null;

  // The API contract requires a UUID-like, printable ASCII key. Keeping the
  // shape deliberately permissive allows test clients to use another stable
  // UUID-like value while still rejecting whitespace and control characters.
  return /^[\x21-\x7e]{16,64}$/.test(value) ? value : null;
}

export function normalizedPayloadKey(
  input: NormalizedCreateTicketInput,
): string {
  return JSON.stringify({
    requesterId: input.requesterId,
    categoryId: input.categoryId,
    relatedSystemId: input.relatedSystemId,
    summary: input.summary,
    requestedPriority: input.requestedPriority,
    description: input.description,
  });
}
